#!/usr/bin/bash
_user=`exec /usr/bin/qubesdb-read /default-user` || _user=user
_cmd='[ -f /tmp/qubes-session-env ]||(echo>>/tmp/qubes-session-waiter $BASHPID&&{ [ -f /tmp/qubes-session-env ]||exec /usr/bin/sleep inf;});. /tmp/qubes-session-env;exec /usr/bin/zenity "$@"'
if [ "`exec /usr/bin/id -un`" = "$_user" ]
then eval "$_cmd"
else exec /usr/sbin/runuser -ls/usr/bin/bash -c "$_cmd" -- "$_user" "$0" "$@"
fi
